/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aspire.studentservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the student service. Represents a row in the &quot;student_table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aspire.studentservice.model.impl.studentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aspire.studentservice.model.impl.studentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see student
 * @generated
 */
@ProviderType
public interface studentModel extends BaseModel<student> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this student.
	 *
	 * @return the ID of this student
	 */
	public long getId();

	/**
	 * Sets the ID of this student.
	 *
	 * @param id the ID of this student
	 */
	public void setId(long id);

	/**
	 * Returns the enrollmentno of this student.
	 *
	 * @return the enrollmentno of this student
	 */
	@AutoEscape
	public String getEnrollmentno();

	/**
	 * Sets the enrollmentno of this student.
	 *
	 * @param enrollmentno the enrollmentno of this student
	 */
	public void setEnrollmentno(String enrollmentno);

	/**
	 * Returns the fname of this student.
	 *
	 * @return the fname of this student
	 */
	@AutoEscape
	public String getFname();

	/**
	 * Sets the fname of this student.
	 *
	 * @param fname the fname of this student
	 */
	public void setFname(String fname);

	/**
	 * Returns the lname of this student.
	 *
	 * @return the lname of this student
	 */
	@AutoEscape
	public String getLname();

	/**
	 * Sets the lname of this student.
	 *
	 * @param lname the lname of this student
	 */
	public void setLname(String lname);

	/**
	 * Returns the contactno of this student.
	 *
	 * @return the contactno of this student
	 */
	@AutoEscape
	public String getContactno();

	/**
	 * Sets the contactno of this student.
	 *
	 * @param contactno the contactno of this student
	 */
	public void setContactno(String contactno);

	/**
	 * Returns the city of this student.
	 *
	 * @return the city of this student
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this student.
	 *
	 * @param city the city of this student
	 */
	public void setCity(String city);

	@Override
	public student cloneWithOriginalValues();

}